---
# OpenSearch configuration file.
cluster.name: aistack
node.name: aistack-00
bootstrap.memory_lock: true
discovery.type: single-node

OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
DISABLE_INSTALL_DEMO_CONFIG: true
DISABLE_SECURITY_PLUGIN: true
...

